### ISSUE TITLE
It takes more than 30 seconds to install the tye extension in VS Code

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-tye#108]
**OS:** Win10
**Build Version:** 20210630.1

**Repro Steps:**
1. Install tye extension in VS Code.
2. Check whether it takes less than 10 seconds to install the tye extension.

**Expect:**
It takes less than 10 seconds to install the tye extension in VS Code.

**Actual:**
It takes more than 30 seconds to install the tye extension in VS Code.

**Comment by pratiksanglikar** [comment]
This is possibly due to the large vsix size.
Item tracked here - #77

**Comment by dbreshears** [comment]
This is handled in #77
