### ISSUE TITLE
The debugging will be auto-stopped in 2 seconds when debugging a project with 2 running tye applications

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-tye#110]
**OS:** Win10
**Build Version:** 20210630.1

**Repro Steps:**
1. Download the project by the command "git clone https://github.com/pratiksanglikar/tye-demo" -> Open the project in VS Code -> F1 -> Task: Run Task -> tye-run.
2. Open a terminal in VS Code and execute command "tye run" for this project again.
3. Navigate to Tye view, there are 2 duplicate tye applications in it.
4. F5 to debug this project with "Debug with Tye" configuration.
5. Check whether succeed to debug the project.

**Expect:**
Succeed to debug this project.

**Actual:**
The debugging will be auto-stopped in 2 seconds when debugging the project.

**More Info:**
This issue does not reproduce with 1 running tye application.

**Comment by philliphoff** [comment]
It looks like Tye doesn't support running the same application twice *when in `watch` mode*; the project build for the second application instance seems to interfere with the first application instance's watch, which causes its replicas to be taken down but unable to be brought back up (and hence, debugging immediately stops).  Also, it look like Tye tries to recycle the Docker containers used by the first application instance.

Running two instances of the same application is probably not going to be a common occurrence, so I'm not *too* concerned about users running into this issue.  At a minimum we'd need Tye to fully support the model first.  I'll mark this as blocked, external for now.

**Comment by dbreshears** [comment]
This doesn't seem to be a scenario that we would support at this time
