### ISSUE TITLE
[Suggestion] It would be better if the opened file is a temporary file when clicking "Logs" for one service

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-tye#116]
**OS:** Win10
**Build Version:** 20210702.3

**Repro Steps:**

1. Download the project by the command "git clone https://github.com/pratiksanglikar/tye-demo" -> Open the project in VS Code -> Select the "Debug with Tye" configuration and F5.
2. Navigate to Tye view and click "Logs" for one service.
3. Check whether the opened file is a temporary file.

**Actual:**
The opened file isn't a temporary file.

**Suggestion:**
It would be better if the opened file is a temporary file, it will be auto-replaced when clicking "Logs" for the other service.

**Comment by philliphoff** [comment]
@v-mengwe Thanks, that's a good suggestion.  There *is* now a way for extensions to signal to VS Code whether an extension-opened file should replace a previously-opened file or open an *additional* file, and we should make sure we're using that signal in a way consistent with VS Code.
