### ISSUE TITLE
The microservice application's debugger is attached when clicking "Attach" button of Dapr application

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-tye#118]
**OS:** Win10
**Build Version:** 20210702.3

**Repro Steps:**

1. Open the `tye-demo` project in VS Code -> F1 -> Tasks: Run Task -> Select "tye-run".(`microservice application`)
2. Open the `tye-dapr-demo` project in a new window -> F1 -> Tasks: Run Task -> Select "tye-run".(`dapr application`)
3. Navigate to Tye view, there are 2 tye applications in it -> Click "Attach" button of **dapr** application.
   ![image](https://user-images.githubusercontent.com/62053665/124574924-86df6e00-de7d-11eb-81e6-d30df11b1dd7.png)
4. Check whether the dapr application's debugger is attached.

**Expect:**
The dapr application's debugger is attached.

**Actual:**
The microservice application's debugger is attached. 
![image](https://user-images.githubusercontent.com/62053665/124575047-a24a7900-de7d-11eb-9b46-8f8f0ad4012c.png)

**Comment by philliphoff** [comment]
@v-mengwe Good catch!  This is, indeed, because the extension was using the old behavior of assuming the first application in its list was the intended application to be debugged (when we only supported a single application at a time).  That assumption no longer holds.
