### ISSUE TITLE
Tye applications running inside a devcontainers aren't visible in the TreeView

### ISSUE THREAD

**Issue by pratiksanglikar** [microsoft/vscode-tye#125]
Issue Type: <b>Bug</b>

1. Create a devcontainer enabled Tye application. (I tested on the microservices-accelerator app)
2. Run the application using the `tye-run` task.
3. Browse to https://localhost:8000 to see if the app has started.
4. Check if the TreeView is updated with the started services.

Extension version: 0.3.0-alpha
VS Code version: Code - Insiders 1.59.0-insider (599f5d2c67571f84a045a59eb3423bc254ee87d9, 2021-07-16T09:56:58.707Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.43.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (13.99GB free)|
|Process Argv|--crash-reporter-id 5efa374b-afb0-449b-a378-e88461e67ccf|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: .NET Core 3.1 with Docker, Dapr, and Tye|
|OS|Linux x64 5.10.43.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|Memory (System)|15.56GB (6.42GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
vshan820:30294714
vscus158:30321503
pythonvsuse255:30319630
3f5j7703:30294757
vscod805cf:30301675
vscextlangct:30310089
vsccppwtct:30312693
bridge0708:30335490

```

</details>

**Comment by philliphoff** [comment]
It looks like it's an issue only when ingress is used; Tye then hosts multiple endpoints (i.e. both the dashboard and ingress endpoints). The extension chooses the first port arbitrarily as the dashboard one; if that happens to be the ingress port, then its calls to what it thinks is the dashboard port will fail (and, hence, the application won't show up in the tree).

It looks like, on Mac/Windows, the dashboard endpoint port generally happens to be the first listed, so it works.  On Linux, however, the ingress port is getting chosen first.  There's no way for the extension to know (after the fact, or if it didn't start Tye directly) which of those ports is which.  (It's logged in the `stdout` on startup, but that's not always available.). We may need to interrogate each endpoint and see which one "looks" like the dashboard port.
