### ISSUE TITLE
No Tye application is running in the Tye Application view after executing tye-run with setting the Tye Path on Windows

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-tye#133]
**OS:** Windows
**Build Version:** 20210721.1
**Regression:** Previous release

**Repro Steps:**
1. Install Tye at a custom path using the following command.
dotnet tool install Microsoft.Tye --version "0.9.0-*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json --tool-path "C:\custom_tye_path"
2. Set the Tye Path setting, like below.
![image](https://user-images.githubusercontent.com/45614674/128164727-431c99df-8229-4fdd-a7bd-14c9a65aadc8.png)
3. Download the project by the command "git clone https://github.com/pratiksanglikar/tye-demo" -> Open the project in VS Code -> Tye-run.
4. Check whether the Tye application is running in the Tye Application view.

**Expect:**
The Tye application is running in the Tye Application view.

**Actual:**
No Tye application is running in the Tye Application view.
![teste](https://user-images.githubusercontent.com/45614674/128164995-348d154b-1526-48c1-ba81-4b6e7aee679e.png)

**More Info:**
1. This issue doesn't reproduce on Mac and Linux.
2. This issue does not reproduce on the previous released Tye extension.
3. There is a same fixed issue for Mac and Linux https://github.com/microsoft/vscode-tye/issues/120.

**Comment by philliphoff** [comment]
The Windows-specific process provider is explicitly adding the ".exe" to the end of the process name being looked for, which is unnecessary when a custom path is set (because we tell the user to set it to the complete path).  We need to ensure that the provider can always expect a complete filename (if not a complete path).
