### ISSUE TITLE
The "Attach" icon next to the name of the replica of the service is inconsistent with the service

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-tye#150]
**OS:** All
**Build Version:** 0.4.0
**Regression:** Previous release

**Repro Steps:**
1. Install tye using the following command.
```
dotnet tool install -g Microsoft.Tye --version "0.10.0-*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
```
2. Download the project by the command "git clone https://github.com/pratiksanglikar/tye-demo" -> Open the project in VS Code -> Tye-run.
3. Navigate to TYE view -> Expand the service, like **backend** -> Check the "Attach" icon next to the name of the replica of the service.
4. Check whether the "Attach" icon next to the name of the replica of the service is consistent with the service.

**Expect:**
The "Attach" icon next to the name of the replica of the service is consistent with the service.
![image](https://user-images.githubusercontent.com/57662131/132653906-e70e223d-0115-4a26-9536-e7178f0cfea6.png)

**Actual:**
The "Attach" icon next to the name of the replica of the service is inconsistent with the service.
![image](https://user-images.githubusercontent.com/57662131/132654121-e5fcbbdf-ba2c-4143-8ba1-a774c508feff.png)

**More Info:**
This issue doesn't reproduce on the previous Tye extension released build.

**Comment by pratiksanglikar** [comment]
Hi @v-xinda, 
It is by design.
The first icon on the `service` node is the `attach all` icon, which will attach to all replicas of that service, and the second icon on the `replica` node is the `attach` icon which will only attach to that specific replica.

**Comment by v-xinda** [comment]
@pratiksanglikar Thank you for your sharing. I opened 1 new bug [155](https://github.com/microsoft/vscode-tye/issues/155) to update the prompt massage "Attach" to "Attach All" for the service of the "Attach" icon.
