### ISSUE TITLE
Only display one task when executing " Tasks: Run Tasks" in multiple tye-run tasks project

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-tye#152]
**OS:** All
**Build Version:** 0.4.0
**Regression:** Not a regression

**Repro Steps:**

1. Install tye using the following command.
    > dotnet tool install -g Microsoft.Tye --version "0.10.0-*" --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json
2. Download the project by the command "git clone https://github.com/pratiksanglikar/tye-demo" -> Open the project in VS Code -> F1 -> Tye: Scaffold Tye Tasks -> Click "Create task" when asking to overwite the task -> Click "Cancle" when asking to overwite the configuration.
3. F1 -> Tasks: Run Tasks.
4. Check whether display all the tye-run tasks.

**Expect:**
Diaplay all the tye-run tasks.

**Actual:**
Only display one task.
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/62053665/132663488-cd245b7e-e82e-4282-a8a7-38f6df8c5083.png)

**More Info:**
There are multiple tye-run tasks in the .vscode/tasks.json file.

**Comment by pratiksanglikar** [comment]
@v-mengwe, the first task that is displayed is the `recently used` task, and it will only show those that are recently used.
If you select `tye-run` with a folder icon (number 5 in your screenshot), it will show you all the tasks.

**Comment by v-mengwe** [comment]
Got it, thanks for your sharing.
