### ISSUE TITLE
There is no "Browse" button for the service which specify the number of replicas

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-tye#153]
**OS:** All
**Build Version:** 20210908.2
**Regression:** Not a regression

**Repro Steps:**
1. Download the project by the command "git clone https://github.com/pratiksanglikar/tye-demo" -> Open the project in VS Code -> Tye-run.
2. Navigate to TYE view -> Check the buttons for the service, there is a "Browse" button for the service.
![![image](https://user-images.githubusercontent.com/45614674/132664508-0c20df37-0539-443d-958d-38ca048993a8.png)](https://user-images.githubusercontent.com/45614674/132664368-232d3771-2fa3-46cd-ab1a-674f53c70406.png)
3. Specify the number of replicas for one service, such as add "replicas: 5" in tye.yaml file -> Tye-run.
4. Navigate to the TYE view -> Check the buttons for the service which specify the number of replicas.
5. Check whether there is a "Browse" button for the service.

**Expect:**
There is a "Browse" button for the service.

**Actual:**
There is no "Browse" button for the service.
![image](https://user-images.githubusercontent.com/45614674/132664582-5dc5458b-bb18-4f9e-acc9-b3aac5bff896.png)

**Comment by dbreshears** [comment]
This is by design due to not knowing which replica would be the ideal replica to browse to.   The design would be to expand and click browse on the individual replica
