### ISSUE TITLE
No Tye application is running in the Tye Applications view - Ubuntu 21.10

### ISSUE THREAD

**Issue by L-Sypniewski** [microsoft/vscode-tye#179]
**OS**: Ubuntu 21.10
**tye**: 0.11.0-alpha.22111.1
**vscode-tye**: v0.5.0

Tye applications are not shown in Tye Applications view regardless if Tye is run directly with `tye run` command or with generated `Debug with Tye` VSCode task. 
I checked out other similar issues and in my case setting Tye path manually in the settings or installing Tye in a custom location doesn't make any difference. It also doesn't matter if VSCode is installed from .deb or as a Snap package.
Applications are shown in the view if I run the project in a default .NET dev container though.

**Comment by albertlinga** [comment]
> I have the same problem. **OS**: Ubuntu 20.04.4 LTS **tye**: 0.11.0-alpha.22111.1 **vscode-tye**: v0.5.0

Same problem with the same version as @PhannDom (only mine is using WSL2). I'm getting an Error: spawn netstat ENOENT just by clicking the Tye sidebar. When running the application using the Debug sidebar I'm getting the same error as well and debugger won't attach but the build continues. I have attached a screen shot of the vs code console
![tye-extension](https://user-images.githubusercontent.com/28690177/159703130-c9e470a9-9008-44d5-a257-a8a8c20d12a0.png)
.

**Comment by albertlinga** [comment]
Update: The issue i'm encountering is because netstat wasn't installed in my ubuntu disto. Had to do sudo apt install net-tools.

**Comment by PhannDom** [comment]
> Update: The issue i'm encountering is because netstat wasn't installed in my ubuntu distro. Had to do sudo apt install net-tools.

Thanks for your solution

**Comment by IanWitham** [comment]
> Update: The issue i'm encountering is because netstat wasn't installed in my ubuntu distro. Had to do sudo apt install net-tools.

I had the same problem. No Tye applications shown when using WSL2 remoting. This solution worked for me 👍

**Comment by albertlinga** [comment]
I’ve read that netstat is deprecated because it’s not maintained. It’s not installed by default anymore on latest versions of linux. SS is the recommended tool instead. Perhaps https://github.com/microsoft/vscode-tye/blob/24eb317b922dda42d1fc4c9ed4e6ef34c91ba434/src/services/portProvider.ts shouldn’t use netstat package and reference a different one for ss.
