### ISSUE TITLE
Is the "Debug with Tye" feature of vscode-tye extension supported on Mac M1

### ISSUE THREAD

**Issue by ahsanhabib91** [microsoft/vscode-tye#196]
My general question is, Is this extension supported on **Mac M1**? or More specifically, the **Debug feature**, specially **Debug feature with multiple services** is supported on **Mac M1**?

**Comment by philliphoff** [comment]
@ahsanhabib91 Yes, it's supported on the M1.  (That's my primary development machine.) If you're having trouble, please file a specific issue with details.

**Comment by ahsanhabib91** [comment]
@philliphoff Thanks. I'm closing the issue.
