### ISSUE TITLE
Error Dialog - No Process with specified id is currently running

### ISSUE THREAD

**Issue by ooeygui** [microsoft/vscode-tye#25]
When I use Tye to debug a multi-container solution with Dapr, I will often get multiple dialogs which say:

When this occurs, it appears that the vscode debugger does not engage, so maybe the container crashed? There is no output to indicate this.

**Comment by philliphoff** [comment]
With #101, we're no longer using `stdout` as a means for detecting changes in the application.  The extension should also not complain as much upon failures to attach, so this issue should likely be resolved at this point.  I'll close it for now, but reopen if the issue persists.
