### ISSUE TITLE
No obvious way to restart tye to pick up config changes

### ISSUE THREAD

**Issue by danegsta** [microsoft/vscode-tye#67]
While re-running the `tye-run` task will prompt to re-start the task, it's not obvious behavior. I'd love to have a button on the Tye panel that would allow me to restart the service.

Extension version: 0.1.0-alpha
VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

**Comment by dbreshears** [comment]
Closing as this is a dupe of dotnet/tye#985
