### ISSUE TITLE
Refresh tree view arrangement

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-tye#96]
We'd like to revisit how different kinds of nodes show up in the tree view and where (e.g. de-emphasize the Dapr and other supporting services in favor of emphasizing the user's own services).

**Comment by philliphoff** [comment]
@BigMorty What do you think about this arrangement?

 - Dashboard moved from being its own node to just an inline command on the application node.
 - Project services (i.e. those declared by the user in the `tye.yaml`) listed directly beneath the application node.
 - Non-project services (i.e. those implicitly created by Tye host or its extensions) listed beneath an Other Services node (and collapsed by default).
 - Other Service node has no icon to better separate the two classes of nodes.

> Note that there are changes needed on the Tye CLI side to fully support this model.  For example, the `redis` and `zipkin` nodes should be "project services" as they're listed in `tye.yaml` but as external; there's not enough information in the service metadata for us to make that distinction, however.

Another question is where the ingress node should go; as it (and there can actually be more than one) can be the main entrypoint for an application, should it be more upfront?

<img width="426" alt="Screenshot 2021-07-19 at 13 48 07" src="https://user-images.githubusercontent.com/6402946/126225365-52ad7bde-8be9-4db1-9ca8-cbab17bb2636.png">

**Comment by philliphoff** [comment]
@BigMorty Here's another iteration, after sketching a Tye CLI change to provide additional metadata about the "source" of a service (i.e. the configuration file, an extension, or the host).  I've also updated the icons to try to better represent services (e.g. server processes, external components, ingress, etc.).

> Note I'm now using the same icon both for services and their replicas.  I think that's ok, actually, but let me know what you think.

<img width="422" alt="Screenshot 2021-07-19 at 16 14 10" src="https://user-images.githubusercontent.com/6402946/126239262-d3d8c534-0a3c-41e5-a25c-2132fd8724a5.png">

**Comment by BigMorty** [comment]
This looks great, ship it! 😀
